version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_ludico
    restart: always
    environment:
      # Estas variables deben coincidir con lo que pongas en tu backend/.env local
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: saas_b2b
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: